#!/usr/bin/env python3
# Generated by MRF Compiler
# Copyright (C) 2025, Shyamal Suhana Chandra

import pennylane as qml
import numpy as np

dev = qml.device('default.qubit', wires=3, shots=1000)

@qml.qnode(dev)
def mrf_circuit():
    """
    Quantum circuit from MRF model.
    Returns: measurement results
    """
    qml.Hadamard(wires=0)
    qml.Hadamard(wires=1)
    qml.Hadamard(wires=2)
    qml.RY(0, wires=0)
    qml.RY(0, wires=1)
    qml.RY(0, wires=2)
    return qml.sample([qml.PauliZ(wires=0), qml.PauliZ(wires=1), qml.PauliZ(wires=2)])

if __name__ == '__main__':
    result = mrf_circuit()
    print('Measurement result:', result)
    print('\nCircuit:')
    print(mrf_circuit.qtape)
